### ISSUE TITLE
Support tvOS / AppleTV target

### ISSUE THREAD

**Issue by brion** [brion/OGVKit#127]
The new AppleTV will have an A8 processor which should decode WebM VP8 fast enough for comfortable playback. Should make sure the OGVKit library supports a tvOS target, and add a tvOS target to the example project.

Depends on CocoaPods support for tvOS (presumably possible, as watchOS 2 is now supported). Upstream bug: https://github.com/CocoaPods/CocoaPods/issues/4149

**Comment by hartman** [comment]
Oh, we could have a Wikipedia free content channel :+1: 
I applied for the devkit already, but I'm not that lucky, i'll just buy the actual device when it's out.
