### ISSUE TITLE
'vpx/vpx_decoder.h' file not found

### ISSUE THREAD

**Issue by kobelb** [brion/OGVKit#131]
The commit to update to a newer version of libvpx has caused the following error to be thrown when building the example app in OGVDecoderWebM.m:  'vpx/vpx_decoder.h' file not found

I've tried to track down exactly what caused the issue, but I've been having trouble tracking it down...

**Comment by brion** [comment]
Might be due to more changes in CocoaPods 0.39's framework support. Will take a peek...

**Comment by brion** [comment]
Ok should be fixed by d9d9faa94761e1f10a9 in the specs repo -- you may need to clear out Podfile.lock & Pods directory and re-run 'pod install'.

**Comment by kobelb** [comment]
Thanks man!!! I really appreciate the library and all of your help!
