### ISSUE TITLE
VP8 with multiple resolutions

### ISSUE THREAD

**Issue by kobelb** [brion/OGVKit#132]
When trying to use this library to play a video that switches the video resolution in the middle of a file (we're recording videos using webrtc which changes the resolution based on network conditions) the video will become distorted and sometimes crash the decoder.

Let me know if a sample video that is causing the issue would be helpful, and the best way to get it to you is. I was unable to attach it to this issue.

**Comment by brion** [comment]
Yes, a sample to test would be great! How big a file are we looking at? Can probably rig something up...

**Comment by brion** [comment]
(In a pinch, you should be able to upload up to a 1gb .webm file onto the MediaWiki test site at https://test.wikipedia.org/wiki/Special:Upload and I can grab it from there, as long as you don't mind it being publicly copyable.)

**Comment by kobelb** [comment]
It's only a megabyte, and pretty poor quality. It just occurred to me that I could put it in google drive and then publicly share it: https://drive.google.com/file/d/0B_CiYpBO6UGXeUNhdTA4T2JVa28/view?usp=sharing let me know if that doesn't work for you

**Comment by kobelb** [comment]
The resolution changes in the sample video are from 2 things:
1) Turning the camera mid recording changes the frame-size, I'm considering limiting this ability
2) While the WebRtc Peer Connection is transferring video it will periodically upgrade/downgrade the quality of the video based on the available bandwidth, and something about spinning around in my chair makes it do so rather frequently...

**Comment by brion** [comment]
Perfect; I've downloaded it and will add to my provisional test suite. :D

Hopefully just a matter of making sure we properly resize the frame buffer & update the aspect ratio when the resolution changes.

**Comment by kobelb** [comment]
I saw that you're hoping to address this as part of the 0.5 API refactor, and I didn't know if this was anything that I could help out with?

We're hoping to use your library in the application that we're building; however, without the multi-resolution support, we're kinda outta luck.

**Comment by brion** [comment]
Just got a chance to poke at it -- looks like the problem is that the videoFormat struct (which carries width/height info) from stream initialization time is always passed as-is into the frame buffers. We need to be able to get the updated widht/height from the decoded frame and pass that in instead. Should be an easy fix, I think... lemme try something real quick and see what happens. :D

**Comment by brion** [comment]
@kobelb try that out, seems to do the job!

**Comment by kobelb** [comment]
Thanks man! I really appreciate it!
