### ISSUE TITLE
Pod installation failure when also using Swift pods

### ISSUE THREAD

**Issue by shirokova** [brion/OGVKit#133]
Unable to install the framework trough Cocoapods when using also swift pods (requires use_frameworks!). Getting error on pod install:
> [!] The 'Pods' target has transitive dependencies that include static binaries: (<...>/Pods/libvpx/VPX.framework)

**Comment by brion** [comment]
Can you provide a quick example project to test with?

**Comment by brion** [comment]
Doing a little research ... https://github.com/CocoaPods/CocoaPods/issues/3194 etc looks like CocoaPods just doesn't support static libraries as dependencies of dependencies if you're using dynamic frameworks as well (which is the only way to package swift modules)... Not quite sure I understand why exactly but that's how it is. :(

I may have to do something fun like see if I can rebuild libvpx as a proper dynamic framework (which would require upping the base iOS version to at least 8).

**Comment by shirokova** [comment]
Well, that might be a good way to solve it. In addition iOS 7 is not supported a lot ))
If you still need example project here it is https://github.com/shirokova/iOS-TestOGV.git

**Comment by brion** [comment]
Ok, I think I got it hacked up to work -- please test! You may have to reinstall the pods.

Modified libvpx build info over on https://github.com/brion/VPX-iOS/issues/2

**Comment by shirokova** [comment]
I was able to install OGV, but I'm getting several issues when I tried to build a project.

First I got a lot of errors like _Unknown type name ‘NSString’_ or _Expected identifier or '(‘_, I fixed it by changing of types of all .c files from _Default - C Source_ to _Objective-C Source_.
Then I got next error
```
ld: '<...>/Pods/libvpx/VPX.framework/VPX' does not contain bitcode. 
You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), 
obtain an updated library from the vendor, 
or disable bitcode for this target. for architecture arm64
```
It might be fixed by setting *Enable Bitcode* to *No* for OGVKit. 

After these changes build was successfully finished, but app installation failed with message _Could not inspect the application package._. I'm trying to figure out the reason :)

**Comment by brion** [comment]
Yeah, to add bitcode on libvpx I need to build it with Xcode 7, but there are some bugs in the build system so it's still built with 6.4. That should be ignorable for now, but I do want to fix it sometime!

Will take a look at the c vs obj-c thing, not sure what's wrong there...

**Comment by brion** [comment]
Looks like an issue with modules -- I may have to specify a manual module map of headers. Looking into it. :) Thanks for helping to exercise the library!

**Comment by brion** [comment]
I'm going to have to poke this a bit more; for the moment I'm reverting the VPX library to the static version so everything on the old system keeps working. Workspace for converting things to be module-friendly over on https://github.com/brion/OGVKit-Specs/tree/frameworks branch ... https://github.com/brion/OGVKit-Specs/issues/1

**Comment by brion** [comment]
Ok as of latest commits it should be working! :D

Couple things:
* first, OGVKit now requires "use_frameworks!" in the using app's Podfile or the VPX library won't link right
* to support dynamic frameworks, min iOS requirement is bumped from 7 to 8
* there may be some warnings about umbrella headers; I still have to refactor some stuff to live better in a dynamic-framework world but it seems harmless!
* in your app's Podfile, you may need to specify the version number of OGVKit to make sure it doesn't whine about it being a prerelease version. This works for me:

```
    pod "OGVKit", '~> 0.5pre'
```

**Comment by shirokova** [comment]
Works perfectly now! Thank you for quick fixing that, Brion :)
