### ISSUE TITLE
Memory leaks?

### ISSUE THREAD

**Issue by newacct** [brion/OGVKit#135]
When I run the Leaks instrument on the example project, it shows a lot of leaks, one in nestegg at app start without doing anything and a bunch in vorbis when playing videos. This happens on both simulator and device. I am using the latest Xcode (7.1.1); the same thing also happens on Xcode 7.2 beta. Does anyone else see this, or is it just me? Are these real leaks or false positives?

**Comment by brion** [comment]
I'll be doing some updates to OGVKit this weekend and will do some instrument runs to double-check for leaks. Thanks for the heads-up!

**Comment by newacct** [comment]
It seems that the problem with the vorbis leaks is that vorbis_dsp_clear() needs to use vorbis_info inside it, so vorbis_info_clear() must be called after vorbis_dsp_clear().

**Comment by newacct** [comment]
And the single halloc leak in nestegg seems to be intentional: https://github.com/kinetiknz/nestegg/commit/59220ae3e801cbad0f8160129c4df315469af671
