### ISSUE TITLE
Useless assignment to variable "silence" in OGVAudioFeeder

### ISSUE THREAD

**Issue by newacct** [brion/OGVKit#138]
In `-[OGVAudioFeeder handleQueue:buffer:]`, there's the following code that doesn't make much sense:
```
int silence = bufferSize;
silence = 1024; // ????
```
(that comment was already there; I didn't add it :) )

**Comment by brion** [comment]
That's setting an arbitrary number of silent samples to send to output; the number is used both immediately in determining how many samples to send, and is saved into samplesOfSilence to use later in compensating our recorded output time.

**Comment by brion** [comment]
ah but there only needs to be one :)
