### ISSUE TITLE
Resize (Crop) played video

### ISSUE THREAD

**Issue by andyshephard** [brion/OGVKit#140]
Seeing as the playback view is managed by OpenGL, do you know if there's a possibility of cropping the video, or splitting it into two views and translating it to a different point in the view?

**Comment by brion** [comment]
Should be pretty doable yeah -- cropping could be done with a small modification to OGVFrameView, while for multi-view stuff you'd probably want to take over more of the display logic.

If the current coupling between the controller layer and the OGVFrameView is too awkward to work with let me know what would help you there and we can see about improving that. :)

**Comment by andyshephard** [comment]
So I managed the cropping by altering the values of `textureRectangle` in the `OGVFrameView setupTexturePosition:width:height` method, and adjusting the height values in the `drawRect` values.

**Comment by brion** [comment]
Going to roll this into https://github.com/brion/OGVKit/issues/178 (exposing videoGravity of the AVSampleBufferDisplayLayer)
