### ISSUE TITLE
Unable to install via cocoapods

### ISSUE THREAD

**Issue by endogenesis** [brion/OGVKit#146]
I get error **[!] Unable to find a specification for `libnestegg` depended upon by `OGVKit/WebMDemuxer`**
My podfile:
```
target ‘Project’ do
pod 'Alamofire', '~> 3.0'
pod ‘OGVKit/WebM’, :git => ‘https://github.com/brion/OGVKit.git’
end
```
Also tried this, and some more option, but every time get errors. 

```
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brion/OGVKit-Specs.git'
target ‘Project’ do
pod 'Alamofire', '~> 3.0'
pod ‘OGVKit’
end
```

**Comment by brion** [comment]
You do need to specify the specs repo in order for the libraries to be found, so the first one that just references OGVKit's repo directly on the package will fail.

The second one *ought* to work, but note that I had an error in the OGVKit.podspec until earlier today -- you might have to run 'pod repo update' and do a fresh 'pod install'. Let me know if that resolves it!

**Comment by endogenesis** [comment]
```
There are only pre-release versions available satisfying the following requirements:

	'OGVKit', '>= 0'

You should explicitly specify the version in order to install a pre-release version
```

Which version i must use?

**Comment by brion** [comment]
0.5pre

**Comment by endogenesis** [comment]
'OGVKit', '0.5pre' work fine. Big thanks. I think its good - update readme for people who have bad knowledge about cocoapods.

**Comment by brion** [comment]
@endogenesis will do! adding that to my todo: https://github.com/brion/OGVKit/issues/147
