### ISSUE TITLE
Won't stream ogg file.

### ISSUE THREAD

**Issue by ajumalebrahim** [brion/OGVKit#149]
I tried playing http://strm.pistache.org:8443/pistache-tel.ogg . So i added like this in source [[OGVLinkedExampleItem alloc] initWithTitle:@"Online OGG file (audio)" URL:[NSURL URLWithString:@"http://strm.pistache.org:8443/pistache-tel.ogg"]]

It is keep fails to stream the file.

**Comment by brion** [comment]
That appears to be a live-style stream... Currently OGVKit supports only seekable HTTP(S) sources; need to add fallbacks to handle local files and non-seekabe HTTP(S) streams.

**Comment by brion** [comment]
Ok, it looks like it might actually work except for this:

```
App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.
```

**Comment by brion** [comment]
Ok, you have to add this to Info.plist, or else specific configurations, check Apple's docs for details:

```
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
```

**Comment by ajumalebrahim** [comment]
Opps, how can i miss the log. Thank you very much Brion.
