### ISSUE TITLE
Subspec "OGVKit/Ogg/Vorbis" fail to build

### ISSUE THREAD

**Issue by c7l8** [brion/OGVKit#151]
Using:

- XCode Version: 7.3

- Tested on CocoaPods Version: 0.39.0

 ---
I just try  ``` pod "OGVKit/Ogg/Vorbis", "0.5pre"``` on a empty project (swift) and I'm getting this error:

<img width="703" alt="screen shot 2016-06-17 at 1 09 00 pm" src="https://cloud.githubusercontent.com/assets/531295/16160333/1d58cf70-348d-11e6-903f-379c1f1f7239.png">

**Comment by brion** [comment]
Ugh, looks like I re-broke subspecs in 6dd62c9f61db7ebeb8635bdfbbf5e764fd20f6b1

**Comment by brion** [comment]
Ok should be fixed between 0b133ec72c903c7923cec85d8dac37c3400f15af and de7f3a187b95490647e10c968abded14555c4903

You'll have to do `pod repo update` then `pod install`.
