### ISSUE TITLE
No decoder, this should not happen.

### ISSUE THREAD

**Issue by BallerChan** [brion/OGVKit#154]
I'm trying to implement OGVKit to use as a video playback for my app splash screen but I am getting the following error: 

2016-07-21 17:21:50.607 myApp[485:133222] RESPONSE 206 RECEIVED (0 available)
2016-07-21 17:21:50.608 myApp[485:133064] no decoder, this should not happen.

I have checked to see that the url is accessible (it downloads a webm file if pasted into the browser). I suspect it's trying to decode the video before it has completed downloading. The file size is 507.43 KB.

**Comment by brion** [comment]
This may also be caused by failure to define the constants in the build definition for the decoders?

**Comment by brion** [comment]
Closing old bug; please reopen if continues with current versions.
