### ISSUE TITLE
 Stream file failed.

### ISSUE THREAD

**Issue by gabormajorszki** [brion/OGVKit#156]
Hello.

When I tried to implement to OGVPlayer to stream ogg audio format, it always fail to stream.

 let playerView = OGVPlayerView(frame: view.bounds)
        view.addSubview(playerView)

```
    playerView.delegate = self
    let url = NSURL(fileURLWithPath: "http://www.loutude.com/loutude/albums/as231sns425/sample.ogg")
    playerView.sourceURL = url as URL!
    playerView.play()
```

Anyone has the same problem?

**Comment by brion** [comment]
Did you whitelist www.loutude.com for non-encrypted HTTP sessions in the Info.plist for your app? Apple's cracked down on external non-encrypted web requests from apps since iOS 8 or so, IIRC.

**Comment by csontosgabor** [comment]
Yes i did

**Comment by csontosgabor** [comment]
Any other idea why doesn't work?thanks

**Comment by brion** [comment]
(closing out old question)
