### ISSUE TITLE
skeleton.h file not fount in OGVKit

### ISSUE THREAD

**Issue by JayBhalani239** [brion/OGVKit#157]
i have install pod "OGVKit" in my project, after completing pod installation when i open workspace and run the project it brings me 1 error that is in bellow image.

![screen shot 2016-11-23 at 3 21 47 pm](https://cloud.githubusercontent.com/assets/23697048/20557242/bcce3ec0-b190-11e6-94ff-24407bd123a6.png)
  
how can i solve this error ,
please help me to solve this out, thanks.

**Comment by brion** [comment]
I cannot reproduce this error with the following steps:

* create new project 'FooTest' in Xcode (iOS single-view application, Objective-C, Universal)
* close xcode
* go to terminal
* go to the directory containing the FooTest.xcodeproj and base dir.
* run 'pod init'
* edit Podfile to contain:
```
source 'https://github.com/CocoaPods/Specs.git'

# This line is needed until OGVKit is fully published to CocoaPods
# Remove once packages published:
source 'https://github.com/brion/OGVKit-Specs.git'

target 'FooTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for FooTest
  pod "OGVKit", "0.5pre"
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```
* run "pod install"
* open the FooTest.xcworkspace in Xcode
* compile

State:
* OS X 10.12.1
* Xcode 8.1
* cocoapods 1.1.1
* ran 'pod repo update' recently

**Comment by JayBhalani239** [comment]
thanks for the replay, i will check and tell you later.

**Comment by daymont87** [comment]
Same issue when running example project:(

<img width="1402" alt="2017-01-25 22 00 09" src="https://cloud.githubusercontent.com/assets/13594019/22304748/c8137666-e349-11e6-9f1c-afbfbcb63dd0.png">

**Comment by brion** [comment]
This does trip a lot of people up, I'll have to make it easier to avoid breaking... Did you run 'git submodule update --init' _before_ 'pod install'? If not, you'll need to re-run I think or it gets confused about the files from the libskeleton submodule.

**Comment by 8ofproject** [comment]
Tried so far in this order:
+ pod repo update
+ git submodule update --init
+ pod install

Still the same error occurs if I try to use *0.5.9* version in Podfile (and *:git* path).
But works for *0.5pre* version.

**Comment by kirilldobr** [comment]
Yep, same here

**Comment by abdulKarim002** [comment]
[OGVKit.zip](https://github.com/brion/OGVKit/files/1167964/OGVKit.zip)
download the OGVKit and place it on your project and make sure the project structure is as the image
<img width="263" alt="screen shot 2017-07-23 at 2 21 15 pm" src="https://user-images.githubusercontent.com/13949425/28498015-539871b0-6fb2-11e7-8b30-0c9b0831ab71.png">

**Comment by brion** [comment]
Since this seems to trip people up a lot, I'm going to redo how the libskeleton bits get integrated (or just rewrite them) in a bit.
