### ISSUE TITLE
Portrait Video with 1280*720 resolution is stretching

### ISSUE THREAD

**Issue by codedreamer46** [brion/OGVKit#168]
Hi,
while playing webm landscape video with resolution 1280*720 video doesn't fit, it's stretched, did anyone faced this issue ?

**Comment by brion** [comment]
Can you provide a sample file? Could be an issue with the handling of the aspect ratio/display size settings.

**Comment by codedreamer46** [comment]
sample file
https://drive.google.com/open?id=0B-jaF52khzOQNmQ5MGwxS3BwaVU

**Comment by codedreamer46** [comment]
@brion can you please update on what's making the video stretched ?
