### ISSUE TITLE
Playing stops when app goes to lock screen

### ISSUE THREAD

**Issue by hoomansanatkar** [brion/OGVKit#170]
Playing ogg file continues when app is in background . but when you push the lock button of device and device shows black screen the sound stops. 
Can you help me solve this problem?
i'm not streaming. I play file from local path and Audio,Air Play and picture in picture capability is selected in my app capabilities section
when device is locked and i'm in lock screen file is playing. but when device is locked and device is showing black screen playing is stopped.

**Comment by Nixsm** [comment]
@hoomansanatkar any progress fixing this issue? I'm currently trying to fix it, but no progress so far.  I'm using OGVPlayerState and I found out that the Audio is being decoded when the phone is locked, however it does not seem to play any sound. Any idea @brion? Is this kit supposed to play audios in background?

**Comment by brion** [comment]
I haven't tested background audio at this point, but it ought to work as long as the app's Info.plist declares the proper backgrounding mode for audio. The larger buffer size might be needed if the app's only being woken at intervals by the system (which is very possible! iOS is pretty aggressive about throttling background apps IIRC)

**Comment by twnaing** [comment]
I have set proper background mode. Playing stops when phone is locked or user pressed home button.
