### ISSUE TITLE
How to download webm as mp4?

### ISSUE THREAD

**Issue by KMamedoff** [brion/OGVKit#172]
I cannot figure it out.

**Comment by brion** [comment]
There's no specific helper tool support for that yet, but roughly what you'd do:

* directly use the OGVDecoder classes...
* create an AVAssetWriter etc via AVFoundation
* pump through the decoder to get packets
* convert them into CMSampleBuffers of the appropriate types
* send those into the AVAssetWriter for conversion to MP4 (H.264/AAC)

**Comment by KMamedoff** [comment]
But how?

**Comment by brion** [comment]
Merging this into https://github.com/brion/OGVKit/issues/213 -- I'll be adding a sample to the example app in a bit, along with API changes to facilitate transcoding.
