### ISSUE TITLE
[!] Unable to find a specification for `libopus` depended upon by `OGVKit/OpusDecoder`

### ISSUE THREAD

**Issue by bibinjacobpulickal** [brion/OGVKit#186]
My podfile: 
`target 'MyProject' do`
  `use_frameworks!`
`source 'https://github.com/brion/OGVKit-Specs.git'`
`pod "OGVKit/WebM"`
`end`

**Comment by brion** [comment]
libopus is packaged separately on CocoaPods: https://cocoapods.org/?q=libopus

If it's not showing up, you might have lost the base CocoaPods specs. Try adding it explicitly in your Podfile:

```
source 'https://github.com/CocoaPods/Specs.git'
```
