### ISSUE TITLE
Playing ogg file pause when app is in background 

### ISSUE THREAD

**Issue by twnaing** [brion/OGVKit#187]
I am using OGVKit to stream ogg vorbis file. I have 

- set `Allow Arbitrary Loads` to `YES` (in `Info.plist`
- set  `Capabilities` and `Required background modes` to 
    1. App plays audio or streams audio/video using AirPlay
    2. App downloads content from the network
- set AudioSession category and set active

But the best thing I could make it to work is pause (on background) and auto resume/play (on foreground).

When the application went to background the followings are called in order.

- applicationWillResignActive
- applicationDidEnterBackground
- ogvPlayerDidPause

The player resume playing after it has regained focus (in the following order

- applicationWillEnterForeground
- ogvPlayerDidPlay
- applicationDidBecomeActive

The nearest thing I get from [Apple](https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/MediaPlaybackGuide/Contents/Resources/en.lproj/RefiningTheUserExperience/RefiningTheUserExperience.html#//apple_ref/doc/uid/TP40016757-CH6-SW9) is 

> If you’re playing audio-only assets, such as MP3 or M4A files, your setup is complete and your app can play background audio. If you need to play the audio portion of a video asset, an additional step is required. If the player’s current item is displaying video on the device's display, playback of the AVPlayer is automatically paused when the app is sent to the background. If you want to continue playing audio, you disconnect the AVPlayer instance from the presentation when entering the background and reconnect it when returning to the foreground 

How can I prevent the OGVPlayer getting paused?

**Comment by twnaing** [comment]
I found this in [OGVPlayerView.m](https://github.com/brion/OGVKit/blob/master/Classes/OGVPlayerView.m#L375)

```
-(void)appDidEnterBackground:(id)obj
{
    [self pause];
}
```
I have to comment that pause to prevent pausing.

Is there any other elegant way to have the same effect?

**Comment by msalihkocak** [comment]
I am also having the same issue, it plays even when the phone is locked and the screen is on. But once screen goes black it stops. Then when I open it I see "starved for audio!" on console.
