### ISSUE TITLE
Compilation Error in Xcode 9

### ISSUE THREAD

**Issue by TimOliver** [brion/OGVKit#188]
Hey folks!

This was totally working the last time I ran it, so I'm blaming Xcode 9 for changing something. XD

I tried installing `OGVKit` via CocoaPods into a project, and then even tried doing an installation and build of the `Example` project, but both yielded the same build error:

![screen shot 2017-09-17 at 12 55 35 am](https://user-images.githubusercontent.com/429119/30514219-2a0d0862-9b43-11e7-822e-306dd01c1f66.png)

Any idea of how to go about fixing this? I'm happy to attempting a PR if I can be pointed in the right direction. :)

**Comment by TimOliver** [comment]
Quick update. Adding `#include <sys/types.h>` inside that macro fixes it and it builds and runs again.

![screen shot 2017-09-17 at 1 08 31 am](https://user-images.githubusercontent.com/429119/30514309-ca53b266-9b44-11e7-9cd4-0ecb342f5c50.png)

Granted this file `os_types.h` belongs to the `libogg` library, which is most likely out of the scope of this project, so this isn't a fantastic solution...

**Comment by rillian** [comment]
Does running `xcode-select --install` fix it? Xcode no longer installs the command line tools in /usr by default. If so, the corresponding SDK path should be added to the Xcode project.

**Comment by andresBrunFever** [comment]
I've run into the same issue, `xcode-select --install` doesn't solve the issue for me :(

**Comment by brion** [comment]
Yeah, sys/types.h seems to work (whereas the unpatched code's inttypes.h caused a "non-modular header" error which was why I patched it out). I'm seeing some other probs though, working them out now....

**Comment by brion** [comment]
I've updated the libogg spec with a new patch against 1.3.2; run `pod repo update` to update the libogg spec and re-run `pod install` on your project (or if manually working with the files, stick an `#include <sys/types.h>` into that 'Mac OS X Framework' section).

**Comment by TimOliver** [comment]
Awesome! Thank you so much for that @brion! I’ll let you know how I go!

**Comment by kenichirofukuda** [comment]
I reported this issue to you on irc #xiph channel previously.
I appreciate your response!!
