### ISSUE TITLE
Maintaining Aspect Ratio When Resizing Player

### ISSUE THREAD

**Issue by TimOliver** [brion/OGVKit#189]
Hello again! Thanks so much for this awesome library! I've had a fantastic time playing it in a new app I'm building.

One thing I'm curious about. I might be using it incorrectly, but I thought I'd ask.

I'm presenting an `OGVPlayerView` full screen in a modal view controller, and set it to match the view controller's view bounds when it rotates. When the movie starts playing in one orientation, it looks great, but if I rotate the device after the movie starts playing, the movie will appear stretched in the new view controller.

This apparently is because the `OGVFrameView` isn't resetting itself for `OGVPlayerView`'s bounds changing.

I managed to fix it in an incredibly hacky way by adding this to `OGVFrameView`: 

```objc
- (void)setFrame:(CGRect)frame {
    [super setFrame:frame];
    [self updateRectangleWidth:self.frame.size.width height:self.frame.size.height];
}
```

Is there a more official way I can go about supporting this? Or is that hacky way not going to break anything else?

Thanks so much for your time!

**Comment by brion** [comment]
Hmm, that ought to work. :) I'll take a look at it tonight or tomorrow...

**Comment by brion** [comment]
Just a note -- I'm switching over from OGVFrameView to the system-provided AVSampleBufferDisplayLayer for the YUV conversion and frame display, so watch out for any regressions on that. (Haven't pushed yet to the specs repo.)

**Comment by TimOliver** [comment]
Oh nice, okay! Good luck with that! I’ll have another play with it when it’s ready. :)
