### ISSUE TITLE
Class OGVPlayerState initWithURL:delegate: coding error

### ISSUE THREAD

**Issue by xq-120** [brion/OGVKit#190]
-(instancetype)initWithURL:(NSURL *)URL
                  delegate:(id<OGVPlayerStateDelegate>)aDelegate
{
    return [self initWithInputStream:[OGVInputStream inputStreamWithURL:URL]
                            delegate:delegate];  //*should be aDelegate
}

**Comment by brion** [comment]
Good catch, thanks!
