### ISSUE TITLE
Control reaches end of non-void function OGVFrameView.m in XCode 9

### ISSUE THREAD

**Issue by ppshein** [brion/OGVKit#191]
Encountered following error while building, 

`Control reaches end of non-void function` at that function, `-(GLuint)updateRectangleWidth:(int)width height:(int)height.`

<img src="https://preview.ibb.co/cUKCMR/Screen_Shot_2017_10_15_at_9_29_18_PM.png" />

**Comment by ferzescu** [comment]
sam here
