### ISSUE TITLE
Typedef redefinition with different types ('union max_align' vs 'long double')

### ISSUE THREAD

**Issue by khoozhiyan1997** [brion/OGVKit#192]
typedef union max_align max_align_t;
I had error on this line on framework libnestegg

![image](https://user-images.githubusercontent.com/15902734/31823624-41ab369a-b5df-11e7-8018-3c17407265f8.png)

**Comment by QingyuHu** [comment]
same problem

**Comment by babac87** [comment]
Same issue here with Xcode9. Tried with Xcode8.3.3 same problem

**Comment by jfrsheriff** [comment]
Same Problem with Xcode 9.1.

**Comment by brion** [comment]
Yep, confirmed this seems to have cropped up since my last maintenance run... looking into it.

**Comment by brion** [comment]
Be sure to run 'pod repo update' then 'pod update', this'll update libnestegg to a version with the fix.
