### ISSUE TITLE
[!] Unable to find a specification for `OGVKit`

### ISSUE THREAD

**Issue by developer-n2** [brion/OGVKit#195]
Dear All,
Please I am not able to add OGVKit using pods, I am getting this error:
"[!] Unable to find a specification for `OGVKit`"

Best regards

**Comment by brion** [comment]
Did you include the temp specs repo in your Podfile per the instructions? The OGVKit spec has not yet been published.

```

# This line is needed until OGVKit is fully published to CocoaPods
# Remove once packages published:
source 'https://github.com/brion/OGVKit-Specs.git'
```
