### ISSUE TITLE
pod OGVKit

### ISSUE THREAD

**Issue by RanaSaleh** [brion/OGVKit#196]
Dear All,
 I am getting the following error
"[!] Unable to find a specification for OGVKit" while I am adding pod OGVKit

Best regards

**Comment by brion** [comment]
Did you include the temp specs repo in your Podfile per the instructions? The OGVKit spec has not yet been published.

```

# This line is needed until OGVKit is fully published to CocoaPods
# Remove once packages published:
source 'https://github.com/brion/OGVKit-Specs.git'
```
