### ISSUE TITLE
Can I use for macOS application?

### ISSUE THREAD

**Issue by huynguyen-n** [brion/OGVKit#202]
As the question, I have a macOS app but it's must play the url with "webm" format. So I tried implement this to project but it's show errors about whole of lib file. Do I have any chance to contributor for this repo support with macOS ? Thanks and cheer!

**Comment by brion** [comment]
Currently the libraries are built for iOS and OGVKit itself uses some UIKit bits which are iOS-only (so far!) but it would be possible to port it over I think. Might do so later...

Note that some other larger frameworks like VLCKit and GStreamer are also available for macOS, in a pinch.
