### ISSUE TITLE
+(OGVInputStream *)inputStreamWithURL:(NSURL *)URL is not available from Swift

### ISSUE THREAD

**Issue by olSolo** [brion/OGVKit#217]
Therefore, I don't see any way to create a proper OGVInputStream

**Comment by brion** [comment]
I haven't tested interop with Swift yet so will have to do some testing. From my recollection of the message name translation rules it should be something like `OGVInputStream.inputStream(URL: foo)` ... ? But it might not be bridging correctly to begin with...

**Comment by olSolo** [comment]
When translating to Swift, it cuts class name also, so it should look like OGVInputStream.(url: foo), which I guess is not valid. 
I added two proxy method + (OGVInputStream *)createWithURL 
and + (OGVInputStream *)createWithData
You can check my pull request https://github.com/brion/OGVKit/pull/218

**Comment by brion** [comment]
Awesome -- I'll try to take a look at the pull req shortly. Thanks!

**Comment by olSolo** [comment]
I don't really like this my solution, but I have no idea how to fix it nicely and keep version compatibility
