### ISSUE TITLE
Library not loaded: libvpx.5.dylib

### ISSUE THREAD

**Issue by mishamoix** [brion/OGVKit#221]
Hi! Got this crash after install from testflight (but from Fabric it work fine)

Termination Description: DYLD, Library not loaded: libvpx.5.dylib | Referenced from: /var/containers/Bundle/Application/A84E5B94-7B0E-4114-8876-12EB9E260E31/MyApp.app/MyApp | Reason: unsafe use of relative rpath libvpx.5.dylib in /var/containers/Bundle/Application/A84E5B94-7B0E-4114-8876-12EB9E260E31/MyApp.app/MyApp with restricted binary
Triggered by Thread:  0

Use swift 4.2

**Comment by osfunapps** [comment]
Same here! can't publish an app with the library cause it use a relative path somewhere in the code
