### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by babac87** [brion/OGVKit#223]
Started getting this issue recently 

`Undefined symbols for architecture x86_64:
  "_vpx_codec_destroy", referenced from:
      -[OGVDecoderWebM dealloc] in OGVDecoderWebM.o
  "_vpx_codec_decode", referenced from:
      -[OGVDecoderWebM decodeFrame] in OGVDecoderWebM.o
  "_vpx_codec_get_frame", referenced from:
      -[OGVDecoderWebM decodeFrame] in OGVDecoderWebM.o
  "_vpx_codec_vp8_dx", referenced from:
      -[OGVDecoderWebM processBegin] in OGVDecoderWebM.o
  "_vpx_codec_vp9_dx", referenced from:
      -[OGVDecoderWebM processBegin] in OGVDecoderWebM.o
  "_vpx_codec_dec_init_ver", referenced from:
      -[OGVDecoderWebM processBegin] in OGVDecoderWebM.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Xcode v. 10.1

This issue displays when trying to build on simulator. Tried on device, I believe only architecture isn't x86_64, but it also fails.

Read this issue (similar to this one) VPX.framework and armv7 #129, but still couldn't resolve this.

**Comment by AntonAlmosov** [comment]
Have you find a solution for this issue?

**Comment by babac87** [comment]
Unfortunatelly no 😞

**Comment by halleygen** [comment]
Check what version of Cocoapods you have. There has been [a bug with cocoapods 1.6.x](https://github.com/CocoaPods/CocoaPods/issues/8519) for a couple of months now that stops certain pods from working. 

You can fix it by downgrading to CP 1.5.3, running `pod deintegrate`, deleting the project's `.xcworkspace` file + derived data, then finally `pod install`.

As of CP 1.7.0-beta2, the bug still exists so who knows when/if it will be fixed.

**Comment by Maareks27** [comment]
Try to set up Valid Architecture to armv7 and armv7s

**Comment by brion** [comment]
I'm not sure if this is from a CocoaPods change or an Xcode change, but it seems that the vendored frameworks `VPX.framework` and `WebM.framework` are not being set up properly to go into the `OGVKit` target.

As a workaround, find them (in the `Pods` project) and in the 'Targets' panel click 'OGVKit':

<img width="1213" alt="Screen Shot 2019-04-02 at 08 58 11" src="https://user-images.githubusercontent.com/103075/55417409-7ebd5900-5525-11e9-9111-8c252a3b4798.png">

**Comment by babac87** [comment]
Update pods -> build -> Build failed ⛔️
Linked VPX.framework to OGVKit (WebM isn't in my pods) -> build -> Success ✅

Thanks for the update 😊
