### ISSUE TITLE
Player seems to leak memory / is not deallocated before video has stopped

### ISSUE THREAD

**Issue by danielmatzke** [brion/OGVKit#40]
When I remove a player view from its super view (and all other strong references to the object), the player seems to live on until the video has stopped (according to instruments' allocations instrument). Could this be because the dispatch queues still live on / keep themselves alive until the video stops? Also switching to a new sourceURL seems not to kill the previous video.

**Comment by brion** [comment]
sourceURL switching should be fixed as of 691a69d. Leaking still needs some cleanup.

**Comment by brion** [comment]
Ok I think I've got this worked out in with a refactored player view/state split in 858b0ae.
